In [1237]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
# print(torch.__version__)

creating tensors

In [1238]:
#scalar
scalars = torch.tensor(7)
scalars

tensor(7)

In [1239]:
print("dimension",scalars.ndim) #number of dimensions
print("normal value of tensor", scalars.item()) #get the value of a scalar tensor as a standard Python number
print("datatype", scalars.dtype) #data type of the tensor
print("shape of the tensor", scalars.shape) #shape of the tensor

dimension 0
normal value of tensor 7
datatype torch.int64
shape of the tensor torch.Size([])


In [1240]:
#Vectors
vectors = torch.tensor([1,0])
vectors

tensor([1, 0])

In [1241]:
print(vectors.ndim)
print(vectors.shape)
print(vectors.dtype)

1
torch.Size([2])
torch.int64


In [1242]:
#Matrix
matrix = torch.tensor([[1,0],[0,1]])
print(matrix)
print("dimension", matrix.ndim)

tensor([[1, 0],
        [0, 1]])
dimension 2


In [1243]:
matrix.shape #umm 2 * 2 matrix

torch.Size([2, 2])

In [1244]:
matrix[0] #first row
matrix[1] #second row

tensor([0, 1])

In [1245]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(TENSOR)
print("dimension", TENSOR.ndim)
print("shape", TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
dimension 3
shape torch.Size([1, 3, 3])


In [1246]:
print("shape", TENSOR.shape)

shape torch.Size([1, 3, 3])


In [1247]:
TENSOR[0] #first 2D matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [1248]:
TENSOR[0][0] #first row of first 2D matrix

tensor([1, 2, 3])

Creating Randon Tensors 

In [1249]:
random_tensor = torch.rand(3,4) #Creates a tensor with shape (3, 4)3 rows 4 columns  filled with random numbers from a uniform distribution over [0, 1)
print(random_tensor)
print("dimension", random_tensor.ndim)

tensor([[0.9591, 0.4224, 0.7054, 0.5044],
        [0.0648, 0.7291, 0.0405, 0.3937],
        [0.5848, 0.5158, 0.8688, 0.2405]])
dimension 2


In [1250]:
#create a random with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(244,244,3)) #height, width, color channels(RGB)
print(random_image_size_tensor.shape)
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([244, 244, 3])
torch.Size([244, 244, 3])
3


In [1251]:
random_num = torch.rand(1,4,3,4) # channel batch rows columns
print(random_num)
print(random_num.shape)

tensor([[[[0.0925, 0.1328, 0.2051, 0.2147],
          [0.1250, 0.6047, 0.1461, 0.9116],
          [0.7135, 0.1143, 0.2194, 0.5607]],

         [[0.3181, 0.5356, 0.6595, 0.8014],
          [0.9416, 0.3473, 0.3600, 0.3279],
          [0.4883, 0.3830, 0.7849, 0.1220]],

         [[0.3320, 0.2977, 0.0148, 0.8379],
          [0.0785, 0.0688, 0.9672, 0.1090],
          [0.1643, 0.1968, 0.5490, 0.0799]],

         [[0.6712, 0.4097, 0.3035, 0.8578],
          [0.2306, 0.8254, 0.0347, 0.8293],
          [0.5994, 0.5746, 0.2773, 0.1638]]]])
torch.Size([1, 4, 3, 4])


Creating tensor with Zeros and Ones 

In [1252]:
#create a tensor of all zeros

zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [1253]:
#create a tensor of all ones
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

creating a range/arange of tensors and tensor-like

In [1254]:
print(torch.arange(0,10)) #similar to python range but returns a tensor
print(torch.arange(0,10,3)) #step size of 2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 3, 6, 9])


In [1255]:
random = torch.arange(start = 0, end = 1000, step = 10)
random

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [1256]:
#creatig tensor like
tensor_like = torch.zeros_like(random)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

dealing with tensors data types

In [1257]:
#float 32 tensor
float_32_tesnor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, #specify the data type you want your tensor to be
                               device=None, #specify the device you want your tensor to be on
                               requires_grad=False) #whether to track gradients for this tensor or not
print(float_32_tesnor)
print(float_32_tesnor.dtype)

tensor([1., 2., 3.])
torch.float32


In [1258]:
float_16_tensor = float_32_tesnor.type(torch.half)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [1259]:
float_64_tensor = float_32_tesnor.type(torch.double)
float_64_tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [1260]:
float_16_tensor * float_64_tensor

tensor([1., 4., 9.], dtype=torch.float64)

In [1261]:
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [1262]:
int_32_tensor * float_32_tesnor

tensor([1., 4., 9.])

Getting info from tensor

In [1263]:
some_tensor = torch.rand(3,4)
print(some_tensor)

#find out some details abot the given above tensor
print("Shape of tensor", some_tensor.shape)
print("data type of tensor", some_tensor.shape)
print("device of tensor", some_tensor.device)
print("dimension of tensor", some_tensor.ndim)

tensor([[0.1927, 0.4599, 0.7057, 0.7018],
        [0.6028, 0.3441, 0.0122, 0.3412],
        [0.0384, 0.8212, 0.7018, 0.8050]])
Shape of tensor torch.Size([3, 4])
data type of tensor torch.Size([3, 4])
device of tensor cpu
dimension of tensor 2


Manipulaing Tensors (Tensors Operations)

In [1264]:
tensor = torch.tensor([1,2,3])
tensor + 100


tensor([101, 102, 103])

In [1265]:
#multiply
tensor * 100

tensor([100, 200, 300])

In [1266]:
#subtract
tensor - 10

tensor([-9, -8, -7])

Matrix Multiplication

In [1267]:
#element wise multiplication
tesnsor = torch.tensor(  [2,4,6])
print(tesnsor * tesnsor)

tensor([ 4, 16, 36])


In [1268]:
#element wise multiplication
tesnsor = torch.tensor([2,4,6])
print(tesnsor * tesnsor)

tensor([ 4, 16, 36])


In [1269]:
#matrix multiplication
print(tesnsor.matmul(tesnsor)) #dot product

tensor(56)


there are two main rule of performing matrix multiplication
1. the inner dimension must match 
(3,2)  @  (3,2) won't work
(2,3)  @  (3,2) will work
(3,2)  @  (2,3) will work

2. the resulting matrix has the shape of the outer dimension
   (3,2)  @  (3,2)  -> (2,2)

In [1270]:
#torch.matmul(torch.rand(3,2), torch.rand(3,2)) #error because shapes are not aligned

In [1271]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)) #correct shapes

tensor([[0.7414, 0.7554, 0.5206],
        [1.3498, 1.0929, 0.7385],
        [0.9839, 0.7949, 0.5370]])

In [1272]:
torch.matmul(torch.rand(3,4),torch.rand(4,3))

tensor([[1.6444, 1.4263, 1.8225],
        [1.0931, 0.8177, 1.4345],
        [0.8177, 0.9506, 1.3972]])

In [1273]:
tensor = torch.matmul(torch.rand(6,4),torch.rand(4,6))
print(tensor)
tensor.shape

tensor([[0.5078, 0.3799, 0.6447, 0.6982, 0.2480, 0.9556],
        [0.7051, 0.5089, 0.8641, 0.7098, 0.3313, 1.1881],
        [0.6769, 0.4593, 0.9499, 0.5358, 0.4757, 1.1123],
        [0.1919, 0.1310, 0.2633, 0.1880, 0.1244, 0.3165],
        [1.4950, 0.9953, 1.9045, 1.4690, 0.7944, 2.2064],
        [0.9975, 0.6289, 1.3649, 0.8344, 0.6566, 1.3909]])


torch.Size([6, 6])

Dealing wit **Shape Errors**

In [1274]:
# tensor_a = torch.tensor([[1,2],
#                          [3,4],
#                          [5,6]])

# tensor_b = torch.tensor([[3,6],
#                          [9,12],
#                          [15,18]])

# tesnsor
# torch.matmul(tensor_a, tensor_b) #error because shapes are not aligned
# #torch.mm(tensor_a, tensor_b) #works same as torch as matmul 



to fix these tesnor shape error or isues, we can manipulate the shape of one of the tensor using a **Transpose**

In [1275]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[3,6],
                         [9,12],
                         [15,18]])

tesnsor
torch.matmul(tensor_a, tensor_b.T) #transpose switches the axes or the dimensions of the given tensor
#torch.mm(tensor_a, tensor_b) #works same as torch as matmul 



tensor([[ 15,  33,  51],
        [ 33,  75, 117],
        [ 51, 117, 183]])

In [1276]:
print(tensor_b.T)

tensor([[ 3,  9, 15],
        [ 6, 12, 18]])


Finding the **Mean** **Max** and **Sum of Tensors** (Tensor Aggregation)

In [1277]:
x = torch.arange(1,100, 10)
print(x)
x.dtype

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])


torch.int64

In [1278]:
x.min() #minimum value of the tensor

tensor(1)

In [1279]:
x.max() #maximum value of the tensor

tensor(91)

In [1280]:
#the torch.mean() function only works on float tensors not with int(it will throw an error)
torch.mean(x.type(torch.float32)) #mean value of the tensor

tensor(46.)

In [1281]:
torch.sum(x), x.sum() #sum of all the values of the tensor

(tensor(460), tensor(460))

Finding the **Positional Min and Max** of tensors

In [1282]:
#finding the positional miin and max
x
print(x.argmin()) #argmin returns the index of the minimum value in the tensor
print(x.argmax()) #argmax returns the index of the maximum value in the tensor

tensor(0)
tensor(9)


**Reshaping Viewing and Stacking  Squeezing Unsqueezing Tensors**
1. Reshaping - reshapes and imnput tensors to a defined shape
2. View - return a view of an input tensor of certain shape but keep the memory as the original tensor
3. Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. Sqeeze - rempves all `1` dimension forn a tensor
5. Unsqueeze - add a `1` dimension to a target tensor
6. Permute - return a view if the input with dimension permuted in a certain way

In [1283]:
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [1284]:
y_reshaped_1 = y.reshape(9,1)
y_reshaped_1, y_reshaped_1.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [1285]:
#add an extra dimension
y_reshaped = y.reshape(3,3)
y_reshaped_1 = y.reshape(9,1)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [1286]:
#change the view
"""changing z changes x because a view is just a different way of looking at the same data,or share the same memory as the original tensor"""
z = y.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [1287]:
#stack tensor on top of each other
y_stacked = torch.stack([y,y,y,y],dim=0) #dim=0 means stack along the rows
y_stacked, y_stacked.shape  

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [1288]:
#stack tensor on top of each other
y_stacked = torch.stack([y,y,y,y],dim=1) #dim=1 means stack along the columns
y_stacked, y_stacked.shape  

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [1289]:
y_reshaped.squeeze()

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [1290]:
#squeeze and unsqueeze
y_squeeze = torch.squeeze(y_reshaped_1) #removes all the dimensions of size 1
y_squeeze, y_squeeze.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [1291]:
y_unsqueezed = torch.unsqueeze(y_squeeze, dim=0) #adds a dimension of size 1 at the specified position
y_unsqueezed, y_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [1292]:
#permute rearanges the dimension of target tensor in a specified order
x_original = torch.rand(224,224,3)
x_original.shape
#permute the original tensor to change the order of dimensions
x_permuted = x_original.permute(2,0,1) #from (height, width, color channels) to (color channels, height, width)
x_permuted.shape, x_permuted

(torch.Size([3, 224, 224]),
 tensor([[[0.9467, 0.7480, 0.8142,  ..., 0.7022, 0.6189, 0.8731],
          [0.4445, 0.9313, 0.9189,  ..., 0.4588, 0.4528, 0.4525],
          [0.2870, 0.2069, 0.4683,  ..., 0.6502, 0.7546, 0.8193],
          ...,
          [0.7436, 0.7569, 0.4935,  ..., 0.9603, 0.0899, 0.6752],
          [0.1705, 0.9681, 0.8288,  ..., 0.5319, 0.2710, 0.0156],
          [0.5096, 0.3758, 0.3326,  ..., 0.3429, 0.9563, 0.1946]],
 
         [[0.8424, 0.4291, 0.6406,  ..., 0.2497, 0.8890, 0.2102],
          [0.7909, 0.5114, 0.0199,  ..., 0.6389, 0.7965, 0.9386],
          [0.9125, 0.3911, 0.5130,  ..., 0.1579, 0.9405, 0.0748],
          ...,
          [0.2437, 0.9041, 0.0261,  ..., 0.6888, 0.7558, 0.3840],
          [0.7747, 0.1183, 0.4417,  ..., 0.6836, 0.7402, 0.0618],
          [0.5363, 0.6903, 0.0744,  ..., 0.1755, 0.5053, 0.4378]],
 
         [[0.3362, 0.9307, 0.2442,  ..., 0.4559, 0.6214, 0.4774],
          [0.6942, 0.5951, 0.8282,  ..., 0.5141, 0.9440, 0.3659],
          [0

**Indexing**

In [1293]:
x = torch.arange(1.,10.).reshape(1,3,3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [1294]:
x[0] #first 2D matrix

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [1295]:
x[0][0] #first row of first 2D matrix

tensor([1., 2., 3.])

In [1296]:
x[0][1] #second row of first 2D matrix

tensor([4., 5., 6.])

In [1297]:
x[0][0][2]

tensor(3.)

In [1298]:
x[0][1][2]

tensor(6.)

In [1299]:
x[0][2][2]

tensor(9.)