In [1]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
# print(torch.__version__)

creating tensors

In [2]:
#scalar
scalars = torch.tensor(7)
scalars

tensor(7)

In [3]:
print("dimension",scalars.ndim) #number of dimensions
print("normal value of tensor", scalars.item()) #get the value of a scalar tensor as a standard Python number
print("datatype", scalars.dtype) #data type of the tensor
print("shape of the tensor", scalars.shape) #shape of the tensor

dimension 0
normal value of tensor 7
datatype torch.int64
shape of the tensor torch.Size([])


In [4]:
#Vectors
vectors = torch.tensor([1,0])
vectors

tensor([1, 0])

In [5]:
print(vectors.ndim)
print(vectors.shape)
print(vectors.dtype)

1
torch.Size([2])
torch.int64


In [6]:
#Matrix
matrix = torch.tensor([[1,0],[0,1]])
print(matrix)
print("dimension", matrix.ndim)

tensor([[1, 0],
        [0, 1]])
dimension 2


In [7]:
matrix.shape #umm 2 * 2 matrix

torch.Size([2, 2])

In [8]:
matrix[0] #first row
matrix[1] #second row

tensor([0, 1])

In [9]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(TENSOR)
print("dimension", TENSOR.ndim)
print("shape", TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
dimension 3
shape torch.Size([1, 3, 3])


In [10]:
print("shape", TENSOR.shape)

shape torch.Size([1, 3, 3])


In [11]:
TENSOR[0] #first 2D matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
TENSOR[0][0] #first row of first 2D matrix

tensor([1, 2, 3])

Creating Randon Tensors 

In [13]:
random_tensor = torch.rand(3,4) #Creates a tensor with shape (3, 4)3 rows 4 columns  filled with random numbers from a uniform distribution over [0, 1)
print(random_tensor)
print("dimension", random_tensor.ndim)

tensor([[0.2607, 0.2876, 0.1947, 0.0930],
        [0.0535, 0.1783, 0.6750, 0.3666],
        [0.7145, 0.4088, 0.9798, 0.8121]])
dimension 2


In [14]:
#create a random with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(244,244,3)) #height, width, color channels(RGB)
print(random_image_size_tensor.shape)
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([244, 244, 3])
torch.Size([244, 244, 3])
3


In [15]:
random_num = torch.rand(1,4,3,4) # channel batch rows columns
print(random_num)
print(random_num.shape)

tensor([[[[5.4975e-01, 6.9364e-01, 2.0743e-02, 2.2956e-01],
          [5.6101e-02, 7.8774e-01, 2.6352e-01, 5.2607e-01],
          [9.2504e-01, 9.1078e-01, 9.2369e-01, 1.2914e-01]],

         [[4.3663e-01, 7.5399e-01, 9.7135e-01, 5.0436e-01],
          [2.6490e-01, 2.8678e-02, 6.1491e-01, 9.6009e-01],
          [6.6486e-01, 2.6590e-04, 7.6923e-01, 8.0519e-02]],

         [[3.7043e-01, 9.1334e-01, 6.2627e-01, 8.1550e-01],
          [2.0133e-01, 4.2213e-01, 8.2822e-01, 8.3108e-01],
          [1.3464e-01, 4.6906e-01, 9.9295e-01, 6.8392e-01]],

         [[7.8683e-01, 7.0267e-01, 3.9380e-01, 9.1100e-01],
          [3.9682e-01, 4.5629e-01, 2.7299e-01, 1.1337e-01],
          [2.0751e-01, 4.4558e-01, 3.4721e-01, 3.7741e-01]]]])
torch.Size([1, 4, 3, 4])


Creating tensor with Zeros and Ones 

In [16]:
#create a tensor of all zeros

zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [17]:
#create a tensor of all ones
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

creating a range/arange of tensors and tensor-like

In [18]:
print(torch.arange(0,10)) #similar to python range but returns a tensor
print(torch.arange(0,10,3)) #step size of 2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 3, 6, 9])


In [19]:
random = torch.arange(start = 0, end = 1000, step = 10)
random

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [20]:
#creatig tensor like
tensor_like = torch.zeros_like(random)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

dealing with tensors data types

In [21]:
#float 32 tensor
float_32_tesnor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, #specify the data type you want your tensor to be
                               device=None, #specify the device you want your tensor to be on
                               requires_grad=False) #whether to track gradients for this tensor or not
print(float_32_tesnor)
print(float_32_tesnor.dtype)

tensor([1., 2., 3.])
torch.float32


In [22]:
float_16_tensor = float_32_tesnor.type(torch.half)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [23]:
float_64_tensor = float_32_tesnor.type(torch.double)
float_64_tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
float_16_tensor * float_64_tensor

tensor([1., 4., 9.], dtype=torch.float64)

In [25]:
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
int_32_tensor * float_32_tesnor

tensor([1., 4., 9.])

Getting info from tensor

In [27]:
some_tensor = torch.rand(3,4)
print(some_tensor)

#find out some details abot the given above tensor
print("Shape of tensor", some_tensor.shape)
print("data type of tensor", some_tensor.shape)
print("device of tensor", some_tensor.device)
print("dimension of tensor", some_tensor.ndim)

tensor([[0.1560, 0.9717, 0.7132, 0.5187],
        [0.5309, 0.1674, 0.0892, 0.7375],
        [0.7731, 0.1675, 0.8246, 0.5861]])
Shape of tensor torch.Size([3, 4])
data type of tensor torch.Size([3, 4])
device of tensor cpu
dimension of tensor 2


Manipulaing Tensors (Tensors Operations)

In [28]:
tensor = torch.tensor([1,2,3])
tensor + 100


tensor([101, 102, 103])

In [29]:
#multiply
tensor * 100

tensor([100, 200, 300])

In [30]:
#subtract
tensor - 10

tensor([-9, -8, -7])

Matrix Multiplication

In [31]:
#element wise multiplication
tesnsor = torch.tensor(  [2,4,6])
print(tesnsor * tesnsor)

tensor([ 4, 16, 36])


In [32]:
#element wise multiplication
tesnsor = torch.tensor([2,4,6])
print(tesnsor * tesnsor)

tensor([ 4, 16, 36])


In [33]:
#matrix multiplication
print(tesnsor.matmul(tesnsor)) #dot product

tensor(56)


there are two main rule of performing matrix multiplication
1. the inner dimension must match 
(3,2)  @  (3,2) won't work
(2,3)  @  (3,2) will work
(3,2)  @  (2,3) will work

2. the resulting matrix has the shape of the outer dimension
   (3,2)  @  (3,2)  -> (2,2)

In [34]:
#torch.matmul(torch.rand(3,2), torch.rand(3,2)) #error because shapes are not aligned

In [35]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)) #correct shapes

tensor([[0.5795, 0.3018, 0.1096],
        [0.8089, 0.9127, 0.7958],
        [0.8060, 0.4755, 0.2254]])

In [36]:
torch.matmul(torch.rand(3,4),torch.rand(4,3))

tensor([[1.0109, 1.0591, 1.2222],
        [0.3586, 0.6085, 0.4155],
        [1.0819, 1.5086, 1.5033]])

In [37]:
tensor = torch.matmul(torch.rand(6,4),torch.rand(4,6))
print(tensor)
tensor.shape

tensor([[1.3925, 0.8231, 0.9259, 0.4881, 1.0350, 1.2109],
        [1.1179, 0.4135, 0.4667, 0.6475, 0.6474, 0.9818],
        [1.2598, 1.0809, 1.1601, 0.1902, 1.1584, 0.9324],
        [2.0477, 0.8703, 0.9101, 1.1836, 1.2009, 1.6354],
        [1.2940, 0.8311, 0.8332, 0.5459, 0.9078, 0.9030],
        [1.7400, 0.7196, 0.7395, 1.0193, 0.9324, 1.4425]])


torch.Size([6, 6])

Dealing wit **Shape Errors**

In [38]:
# tensor_a = torch.tensor([[1,2],
#                          [3,4],
#                          [5,6]])

# tensor_b = torch.tensor([[3,6],
#                          [9,12],
#                          [15,18]])

# tesnsor
# torch.matmul(tensor_a, tensor_b) #error because shapes are not aligned
# #torch.mm(tensor_a, tensor_b) #works same as torch as matmul 



to fix these tesnor shape error or isues, we can manipulate the shape of one of the tensor using a **Transpose**

In [39]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[3,6],
                         [9,12],
                         [15,18]])

tesnsor
torch.matmul(tensor_a, tensor_b.T) #transpose switches the axes or the dimensions of the given tensor
#torch.mm(tensor_a, tensor_b) #works same as torch as matmul 



tensor([[ 15,  33,  51],
        [ 33,  75, 117],
        [ 51, 117, 183]])

In [40]:
print(tensor_b.T)

tensor([[ 3,  9, 15],
        [ 6, 12, 18]])


Finding the **Mean** **Max** and **Sum of Tensors** (Tensor Aggregation)

In [41]:
x = torch.arange(1,100, 10)
print(x)
x.dtype

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])


torch.int64

In [42]:
x.min() #minimum value of the tensor

tensor(1)

In [43]:
x.max() #maximum value of the tensor

tensor(91)

In [44]:
#the torch.mean() function only works on float tensors not with int(it will throw an error)
torch.mean(x.type(torch.float32)) #mean value of the tensor

tensor(46.)

In [45]:
torch.sum(x), x.sum() #sum of all the values of the tensor

(tensor(460), tensor(460))

Finding the **Positional Min and Max** of tensors

In [46]:
#finding the positional miin and max
x
print(x.argmin()) #argmin returns the index of the minimum value in the tensor
print(x.argmax()) #argmax returns the index of the maximum value in the tensor

tensor(0)
tensor(9)


**Reshaping Viewing and Stacking  Squeezing Unsqueezing Tensors**
1. Reshaping - reshapes and imnput tensors to a defined shape
2. View - return a view of an input tensor of certain shape but keep the memory as the original tensor
3. Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. Sqeeze - rempves all `1` dimension forn a tensor
5. Unsqueeze - add a `1` dimension to a target tensor
6. Permute - return a view if the input with dimension permuted in a certain way

In [47]:
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
y_reshaped_1 = y.reshape(9,1)
y_reshaped_1, y_reshaped_1.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [49]:
#add an extra dimension
y_reshaped = y.reshape(3,3)
y_reshaped_1 = y.reshape(9,1)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [50]:
#change the view
"""changing z changes x because a view is just a different way of looking at the same data,or share the same memory as the original tensor"""
z = y.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
#stack tensor on top of each other
y_stacked = torch.stack([y,y,y,y],dim=0) #dim=0 means stack along the rows
y_stacked, y_stacked.shape  

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [52]:
#stack tensor on top of each other
y_stacked = torch.stack([y,y,y,y],dim=1) #dim=1 means stack along the columns
y_stacked, y_stacked.shape  

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [53]:
y_reshaped.squeeze()

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [54]:
#squeeze and unsqueeze
y_squeeze = torch.squeeze(y_reshaped_1) #removes all the dimensions of size 1
y_squeeze, y_squeeze.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
y_unsqueezed = torch.unsqueeze(y_squeeze, dim=0) #adds a dimension of size 1 at the specified position
y_unsqueezed, y_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [56]:
#permute rearanges the dimension of target tensor in a specified order
x_original = torch.rand(224,224,3)
x_original.shape
#permute the original tensor to change the order of dimensions
x_permuted = x_original.permute(2,0,1) #from (height, width, color channels) to (color channels, height, width)
x_permuted.shape, x_permuted

(torch.Size([3, 224, 224]),
 tensor([[[9.0769e-01, 2.6371e-01, 2.8564e-01,  ..., 7.1123e-01,
           8.1778e-04, 4.6461e-01],
          [8.1116e-01, 7.6732e-01, 9.5911e-01,  ..., 2.8891e-01,
           5.8258e-01, 4.3294e-01],
          [4.7790e-01, 8.5404e-01, 3.9105e-01,  ..., 7.7019e-03,
           4.5331e-01, 4.0813e-01],
          ...,
          [8.6020e-01, 3.8983e-01, 5.7262e-01,  ..., 4.1219e-01,
           2.4104e-01, 3.2560e-01],
          [1.1934e-01, 9.0965e-01, 6.0113e-01,  ..., 7.5867e-01,
           2.0564e-01, 7.9822e-01],
          [6.5335e-01, 7.2561e-01, 2.6666e-01,  ..., 7.0930e-01,
           6.0894e-01, 8.4740e-01]],
 
         [[5.5251e-01, 2.4212e-01, 7.2077e-01,  ..., 1.6470e-02,
           3.9369e-01, 6.3257e-01],
          [4.1580e-01, 8.8997e-01, 8.2728e-01,  ..., 7.7531e-02,
           1.8216e-01, 8.9414e-02],
          [6.0461e-01, 6.8439e-01, 1.8262e-01,  ..., 4.7748e-01,
           1.4453e-01, 4.0962e-01],
          ...,
          [6.9433e-01, 4.0218e

**Indexing**

In [57]:
x = torch.arange(1.,10.).reshape(1,3,3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [58]:
x[0] #first 2D matrix

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [59]:
x[0][0] #first row of first 2D matrix

tensor([1., 2., 3.])

In [60]:
x[0][1] #second row of first 2D matrix

tensor([4., 5., 6.])

In [61]:
x[0][0][2]

tensor(3.)

In [62]:
x[0][1][2]

tensor(6.)

In [63]:
x[0][2][2]

tensor(9.)