In [1170]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
# print(torch.__version__)

creating tensors

In [1171]:
#scalar
scalars = torch.tensor(7)
scalars

tensor(7)

In [1172]:
print("dimension",scalars.ndim) #number of dimensions
print("normal value of tensor", scalars.item()) #get the value of a scalar tensor as a standard Python number
print("datatype", scalars.dtype) #data type of the tensor
print("shape of the tensor", scalars.shape) #shape of the tensor

dimension 0
normal value of tensor 7
datatype torch.int64
shape of the tensor torch.Size([])


In [1173]:
#Vectors
vectors = torch.tensor([1,0])
vectors

tensor([1, 0])

In [1174]:
print(vectors.ndim)
print(vectors.shape)
print(vectors.dtype)

1
torch.Size([2])
torch.int64


In [1175]:
#Matrix
matrix = torch.tensor([[1,0],[0,1]])
print(matrix)
print("dimension", matrix.ndim)

tensor([[1, 0],
        [0, 1]])
dimension 2


In [1176]:
matrix.shape #umm 2 * 2 matrix

torch.Size([2, 2])

In [1177]:
matrix[0] #first row
matrix[1] #second row

tensor([0, 1])

In [1178]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(TENSOR)
print("dimension", TENSOR.ndim)
print("shape", TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
dimension 3
shape torch.Size([1, 3, 3])


In [1179]:
print("shape", TENSOR.shape)

shape torch.Size([1, 3, 3])


In [1180]:
TENSOR[0] #first 2D matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [1181]:
TENSOR[0][0] #first row of first 2D matrix

tensor([1, 2, 3])

Creating Randon Tensors 

In [1182]:
random_tensor = torch.rand(3,4) #Creates a tensor with shape (3, 4)3 rows 4 columns  filled with random numbers from a uniform distribution over [0, 1)
print(random_tensor)
print("dimension", random_tensor.ndim)

tensor([[0.5600, 0.7513, 0.6759, 0.5685],
        [0.6044, 0.1024, 0.9888, 0.5165],
        [0.3646, 0.2470, 0.2838, 0.5853]])
dimension 2


In [1183]:
#create a random with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(244,244,3)) #height, width, color channels(RGB)
print(random_image_size_tensor.shape)
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([244, 244, 3])
torch.Size([244, 244, 3])
3


In [1184]:
random_num = torch.rand(1,4,3,4) # channel batch rows columns
print(random_num)
print(random_num.shape)

tensor([[[[0.2262, 0.0444, 0.8383, 0.9292],
          [0.6681, 0.3285, 0.2011, 0.2265],
          [0.7690, 0.2374, 0.5138, 0.2128]],

         [[0.1513, 0.1060, 0.3756, 0.4024],
          [0.4320, 0.3921, 0.8397, 0.9007],
          [0.1453, 0.4262, 0.4018, 0.6183]],

         [[0.3529, 0.3398, 0.8449, 0.4393],
          [0.6609, 0.2371, 0.0621, 0.5038],
          [0.1403, 0.7219, 0.2784, 0.0567]],

         [[0.7249, 0.5440, 0.3806, 0.3092],
          [0.5735, 0.3567, 0.0018, 0.0074],
          [0.0508, 0.3245, 0.8191, 0.9285]]]])
torch.Size([1, 4, 3, 4])


Creating tensor with Zeros and Ones 

In [1185]:
#create a tensor of all zeros

zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [1186]:
#create a tensor of all ones
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

creating a range/arange of tensors and tensor-like

In [1187]:
print(torch.arange(0,10)) #similar to python range but returns a tensor
print(torch.arange(0,10,3)) #step size of 2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 3, 6, 9])


In [1188]:
random = torch.arange(start = 0, end = 1000, step = 10)
random

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [1189]:
#creatig tensor like
tensor_like = torch.zeros_like(random)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

dealing with tensors data types

In [1190]:
#float 32 tensor
float_32_tesnor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, #specify the data type you want your tensor to be
                               device=None, #specify the device you want your tensor to be on
                               requires_grad=False) #whether to track gradients for this tensor or not
print(float_32_tesnor)
print(float_32_tesnor.dtype)

tensor([1., 2., 3.])
torch.float32


In [1191]:
float_16_tensor = float_32_tesnor.type(torch.half)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [1192]:
float_64_tensor = float_32_tesnor.type(torch.double)
float_64_tensor

tensor([1., 2., 3.], dtype=torch.float64)

In [1193]:
float_16_tensor * float_64_tensor

tensor([1., 4., 9.], dtype=torch.float64)

In [1194]:
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [1195]:
int_32_tensor * float_32_tesnor

tensor([1., 4., 9.])

Getting info from tensor

In [1196]:
some_tensor = torch.rand(3,4)
print(some_tensor)

#find out some details abot the given above tensor
print("Shape of tensor", some_tensor.shape)
print("data type of tensor", some_tensor.shape)
print("device of tensor", some_tensor.device)
print("dimension of tensor", some_tensor.ndim)

tensor([[0.7624, 0.5724, 0.0298, 0.6360],
        [0.8953, 0.1715, 0.4079, 0.7447],
        [0.9628, 0.2692, 0.2166, 0.6972]])
Shape of tensor torch.Size([3, 4])
data type of tensor torch.Size([3, 4])
device of tensor cpu
dimension of tensor 2


Manipulaing Tensors (Tensors Operations)

In [1197]:
tensor = torch.tensor([1,2,3])
tensor + 100


tensor([101, 102, 103])

In [1198]:
#multiply
tensor * 100

tensor([100, 200, 300])

In [1199]:
#subtract
tensor - 10

tensor([-9, -8, -7])

Matrix Multiplication

In [1200]:
#element wise multiplication
tesnsor = torch.tensor(  [2,4,6])
print(tesnsor * tesnsor)

tensor([ 4, 16, 36])


In [1201]:
#element wise multiplication
tesnsor = torch.tensor([2,4,6])
print(tesnsor * tesnsor)

tensor([ 4, 16, 36])


In [1202]:
#matrix multiplication
print(tesnsor.matmul(tesnsor)) #dot product

tensor(56)


there are two main rule of performing matrix multiplication
1. the inner dimension must match 
(3,2)  @  (3,2) won't work
(2,3)  @  (3,2) will work
(3,2)  @  (2,3) will work

2. the resulting matrix has the shape of the outer dimension
   (3,2)  @  (3,2)  -> (2,2)

In [1203]:
#torch.matmul(torch.rand(3,2), torch.rand(3,2)) #error because shapes are not aligned

In [1204]:
torch.matmul(torch.rand(3,2), torch.rand(2,3)) #correct shapes

tensor([[0.5308, 0.2971, 0.2389],
        [0.3717, 0.2284, 0.1738],
        [0.5760, 0.3294, 0.2615]])

In [1205]:
torch.matmul(torch.rand(3,4),torch.rand(4,3))

tensor([[0.5186, 0.9990, 1.1183],
        [1.1121, 1.2156, 1.0187],
        [1.1111, 1.2940, 1.1777]])

In [1206]:
tensor = torch.matmul(torch.rand(6,4),torch.rand(4,6))
print(tensor)
tensor.shape

tensor([[2.3474, 1.7394, 0.9182, 1.7712, 1.8457, 1.1338],
        [1.2644, 0.6864, 0.5370, 1.5535, 1.4986, 0.8973],
        [1.7313, 1.4403, 0.6391, 0.9568, 1.0356, 0.6536],
        [0.8934, 0.6283, 0.3584, 0.7275, 0.7482, 0.4688],
        [1.9163, 1.1944, 0.8003, 1.8298, 1.8109, 1.1736],
        [0.7090, 0.4881, 0.2423, 0.8048, 0.7052, 0.3843]])


torch.Size([6, 6])

Dealing wit **Shape Errors**

In [1207]:
# tensor_a = torch.tensor([[1,2],
#                          [3,4],
#                          [5,6]])

# tensor_b = torch.tensor([[3,6],
#                          [9,12],
#                          [15,18]])

# tesnsor
# torch.matmul(tensor_a, tensor_b) #error because shapes are not aligned
# #torch.mm(tensor_a, tensor_b) #works same as torch as matmul 



to fix these tesnor shape error or isues, we can manipulate the shape of one of the tensor using a **Transpose**

In [1208]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[3,6],
                         [9,12],
                         [15,18]])

tesnsor
torch.matmul(tensor_a, tensor_b.T) #transpose switches the axes or the dimensions of the given tensor
#torch.mm(tensor_a, tensor_b) #works same as torch as matmul 



tensor([[ 15,  33,  51],
        [ 33,  75, 117],
        [ 51, 117, 183]])

In [1209]:
print(tensor_b.T)

tensor([[ 3,  9, 15],
        [ 6, 12, 18]])


Finding the **Mean** **Max** and **Sum of Tensors** (Tensor Aggregation)

In [1210]:
x = torch.arange(1,100, 10)
print(x)
x.dtype

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])


torch.int64

In [1211]:
x.min() #minimum value of the tensor

tensor(1)

In [1212]:
x.max() #maximum value of the tensor

tensor(91)

In [1213]:
#the torch.mean() function only works on float tensors not with int(it will throw an error)
torch.mean(x.type(torch.float32)) #mean value of the tensor

tensor(46.)

In [1214]:
torch.sum(x), x.sum() #sum of all the values of the tensor

(tensor(460), tensor(460))

Finding the **Positional Min and Max** of tensors

In [1215]:
#finding the positional miin and max
x
print(x.argmin()) #argmin returns the index of the minimum value in the tensor
print(x.argmax()) #argmax returns the index of the maximum value in the tensor

tensor(0)
tensor(9)


**Reshaping Viewing and Stacking  Squeezing Unsqueezing Tensors**
1. Reshaping - reshapes and imnput tensors to a defined shape
2. View - return a view of an input tensor of certain shape but keep the memory as the original tensor
3. Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
4. Sqeeze - rempves all `1` dimension forn a tensor
5. Unsqueeze - add a `1` dimension to a target tensor
6. Permute - return a view if the input with dimension permuted in a certain way

In [1216]:
y = torch.arange(1., 10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [1217]:
y_reshaped_1 = y.reshape(9,1)
y_reshaped_1, y_reshaped_1.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [1218]:
#add an extra dimension
y_reshaped = y.reshape(3,3)
y_reshaped_1 = y.reshape(9,1)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [1219]:
#change the view
"""changing z changes x because a view is just a different way of looking at the same data,or share the same memory as the original tensor"""
z = y.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [1220]:
#stack tensor on top of each other
y_stacked = torch.stack([y,y,y,y],dim=0) #dim=0 means stack along the rows
y_stacked, y_stacked.shape  

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [1221]:
#stack tensor on top of each other
y_stacked = torch.stack([y,y,y,y],dim=1) #dim=1 means stack along the columns
y_stacked, y_stacked.shape  

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [1222]:
y_reshaped.squeeze()

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [1223]:
#squeeze and unsqueeze
y_squeeze = torch.squeeze(y_reshaped_1) #removes all the dimensions of size 1
y_squeeze, y_squeeze.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [1224]:
y_unsqueezed = torch.unsqueeze(y_squeeze, dim=0) #adds a dimension of size 1 at the specified position
y_unsqueezed, y_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [1225]:
#permute rearanges the dimension of target tensor in a specified order
x_original = torch.rand(224,224,3)
x_original.shape
#permute the original tensor to change the order of dimensions
x_permuted = x_original.permute(2,0,1) #from (height, width, color channels) to (color channels, height, width)
x_permuted.shape, x_permuted

(torch.Size([3, 224, 224]),
 tensor([[[0.7255, 0.0397, 0.0558,  ..., 0.3419, 0.8438, 0.9807],
          [0.2409, 0.1263, 0.6832,  ..., 0.1268, 0.0825, 0.5119],
          [0.1737, 0.9000, 0.5767,  ..., 0.7049, 0.3173, 0.3581],
          ...,
          [0.2151, 0.4957, 0.4323,  ..., 0.6620, 0.6194, 0.6064],
          [0.0166, 0.8120, 0.9544,  ..., 0.1964, 0.2162, 0.1848],
          [0.2107, 0.0201, 0.9938,  ..., 0.9963, 0.6881, 0.7213]],
 
         [[0.8321, 0.9663, 0.2873,  ..., 0.0748, 0.3826, 0.4766],
          [0.4873, 0.4066, 0.9572,  ..., 0.2263, 0.0179, 0.5568],
          [0.3267, 0.8353, 0.4100,  ..., 0.0687, 0.4370, 0.0186],
          ...,
          [0.2263, 0.0186, 0.6308,  ..., 0.5515, 0.0301, 0.2934],
          [0.9296, 0.9429, 0.3835,  ..., 0.4663, 0.6479, 0.9661],
          [0.8225, 0.9074, 0.8672,  ..., 0.7425, 0.4009, 0.5947]],
 
         [[0.9440, 0.6581, 0.2273,  ..., 0.9354, 0.9876, 0.3390],
          [0.3619, 0.0376, 0.5495,  ..., 0.7371, 0.0424, 0.5490],
          [0

**Indexing**

In [1229]:
x = torch.arange(1.,10.).reshape(1,3,3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [1230]:
x[0] #first 2D matrix

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [1232]:
x[0][0] #first row of first 2D matrix

tensor([1., 2., 3.])

In [ ]:
x[0][1] #second row of first 2D matrix

tensor([4., 5., 6.])

In [1234]:
x[0][0][2]

tensor(3.)

In [1235]:
x[0][1][2]

tensor(6.)

In [1236]:
x[0][2][2]

tensor(9.)