In [ ]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
# print(torch.__version__)

2.8.0


creating tensors

In [3]:
#scalar
scalars = torch.tensor(7)
scalars

tensor(7)

In [9]:
print("dimension",scalars.ndim) #number of dimensions
print("normal value of tensor", scalars.item()) #get the value of a scalar tensor as a standard Python number
print("datatype", scalars.dtype) #data type of the tensor
print("shape of the tensor", scalars.shape) #shape of the tensor

dimension 0
normal value of tensor 7
datatype torch.int64
shape of the tensor torch.Size([])


In [ ]:
#Vectors
vectors = torch.tensor([1,0])
vectors

1

In [13]:
print(vectors.ndim)
print(vectors.shape)
print(vectors.dtype)

1
torch.Size([2])
torch.int64


In [19]:
#Matrix
matrix = torch.tensor([[1,0],[0,1]])
print(matrix)
print("dimension", matrix.ndim)

tensor([[1, 0],
        [0, 1]])
dimension 2


In [ ]:
matrix.shape #umm 2 * 2 matrix

torch.Size([2, 2])

In [29]:
matrix[0] #first row
matrix[1] #second row

tensor([0, 1])

In [31]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
print(TENSOR)
print("dimension", TENSOR.ndim)
print("shape", TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
dimension 3
shape torch.Size([1, 3, 3])


In [32]:
print("shape", TENSOR.shape)

shape torch.Size([1, 3, 3])


In [33]:
TENSOR[0] #first 2D matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
TENSOR[0][0] #first row of first 2D matrix

tensor([1, 2, 3])

Creating Randon Tensors 

In [38]:
random_tensor = torch.rand(3,4) #Creates a tensor with shape (3, 4)3 rows 4 columns  filled with random numbers from a uniform distribution over [0, 1)
print(random_tensor)
print("dimension", random_tensor.ndim)

tensor([[0.4363, 0.4196, 0.0376, 0.1614],
        [0.9416, 0.2150, 0.8206, 0.7284],
        [0.4093, 0.0779, 0.3763, 0.3635]])
dimension 2


In [42]:
#create a random with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(244,244,3)) #height, width, color channels(RGB)
print(random_image_size_tensor.shape)
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([244, 244, 3])
torch.Size([244, 244, 3])
3


In [47]:
random_num = torch.rand(1,4,3,4) # channel batch rows columns
print(random_num)
print(random_num.shape)

tensor([[[[0.1037, 0.5414, 0.1511, 0.1313],
          [0.1206, 0.2040, 0.6620, 0.6104],
          [0.5223, 0.7968, 0.4391, 0.7022]],

         [[0.8259, 0.0052, 0.1819, 0.2015],
          [0.9128, 0.2889, 0.2896, 0.6180],
          [0.6398, 0.4745, 0.1272, 0.8014]],

         [[0.5819, 0.7265, 0.5156, 0.3152],
          [0.4400, 0.4418, 0.7635, 0.2758],
          [0.4582, 0.6198, 0.7537, 0.8674]],

         [[0.1748, 0.0122, 0.7195, 0.9825],
          [0.1945, 0.1436, 0.5474, 0.0481],
          [0.7423, 0.6362, 0.2607, 0.6865]]]])
torch.Size([1, 4, 3, 4])


Creating tensor with Zeros and Ones 

In [50]:
#create a tensor of all zeros

zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [51]:
#create a tensor of all ones
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

creating a range/arange of tensors and tensor-like

In [54]:
print(torch.arange(0,10)) #similar to python range but returns a tensor
print(torch.arange(0,10,3)) #step size of 2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 3, 6, 9])


In [57]:
random = torch.arange(start = 0, end = 1000, step = 10)
random

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [62]:
#creatig tensor like
tensor_like = torch.zeros_like(random)
tensor_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

dealing with tensors data types

In [ ]:
#float 32 tensor
float_32_tesnor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, #specify the data type you want your tensor to be
                               device=None, #specify the device you want your tensor to be on
                               requires_grad=False) #whether to track gradients for this tensor or not
print(float_32_tesnor)
print(float_32_tesnor.dtype)

tensor([1., 2., 3.])
torch.float32


In [65]:
float_16_tensor = float_32_tesnor.type(torch.half)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [66]:
float_64_tensor = float_32_tesnor.type(torch.double)
float_64_tensor

tensor([1., 2., 3.], dtype=torch.float64)